Repository datavisyn/visyn_scripts, pull requests merged in 2024-04, with the labels that each got.

#65 fix: add sassOptions.outputStyle to expanded in rspack.config.js
  config/rspack.config.js
Labels: release: patch, type: bug

#71 feat: disable swc mangle as it creates build errors
  config/rspack.config.js
Labels: release: patch

#73 feat: allow disabling devtool
  config/rspack.config.js
Labels: release: patch

#67 Refactor: remove security routes proxy
  config/rspack.config.js
Labels: type: refactor

#74 Release 9.0.0
  config/rspack.config.js
  package.json
Labels: release: major
