Repository datavisyn/visyn_scripts, pull requests merged in 2024-09, with the labels that each got.

#84 feat: rspack 1.0.0
  config/eslintrc.template.js
  config/rspack.config.js
  package.json
  tests_fixtures/standalone_template/yarn.lock
Labels: release: major, dependencies

#87 deps: remove storybook
  config/eslintrc.template.js
  package.json
  tests_fixtures/standalone_template/package.json
  tests_fixtures/standalone_template/yarn.lock
Labels: release: minor, dependencies

#97 feat: enable tile graph for RS Doctor in rspack.config.js
  config/rspack.config.js
Labels: release: patch, type: technical debt
