Repository datavisyn/visyn_scripts, pull requests merged in 2025-01, with the labels that each got.

#113 feat: Added useTriggerFrame, useDeepEffect and useDeepMemo to exhaustive deps
  config/eslintrc.template.js
  package.json
Labels: release: minor, type: feature

#112 deps: rspack v1.1, TypeScript v5.7, ESLint v8, ...
  .yarn/releases/yarn-4.1.0.cjs
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  bin/commands/lint.js
  config/eslintrc.template.js
  config/rspack.config.js
  package.json
  tests_fixtures/standalone_template/.yarn/releases/yarn-4.1.0.cjs
  tests_fixtures/standalone_template/.yarn/releases/yarn-4.6.0.cjs
  tests_fixtures/standalone_template/.yarnrc.yml
  tests_fixtures/standalone_template/package.json
  tests_fixtures/standalone_template/yarn.lock
Labels: release: major, dependencies

#108 feat: rspack in storybook 8
  config/storybook.main.template.js
  config/storybook.rsbuild.config.ts
  package.json
  tests_fixtures/standalone_template/.storybook/preview.jsx
  tests_fixtures/standalone_template/package.json
  tests_fixtures/standalone_template/yarn.lock
Labels: release: major, type: feature, dependencies

#115 deps: upgrade template to storybook 8.5
  tests_fixtures/standalone_template/package.json
  tests_fixtures/standalone_template/yarn.lock
Labels: release: patch, type: technical debt

#117 fix: add runtimeChunk single to fix HMR
  config/rspack.config.js
Labels: release: patch, type: bug

#120 deps: switch to ts-checker-rspack-plugin
  config/rspack.config.js
  package.json
  tests_fixtures/standalone_template/yarn.lock
Labels: release: minor, dependencies
