Repository datavisyn/visyn_scripts, pull requests merged in 2025-03, with the labels that each got.

#128 fix: no-unused-vars warning shown twice
  config/eslintrc.template.js
Labels: release: minor, type: bug

#122 fix: set exhaustive-deps to error instead of warn
  config/eslintrc.template.js
Labels: release: major, type: refactor

#131 feat: add no-restricted-imports rule for lodash and fontawesome
  config/eslintrc.template.js
Labels: release: major, type: feature

#133 feat: add __APP_NAME__ and __APP_DISPLAY_NAME__
  config/rspack.config.js
Labels: release: patch, type: feature

#136 deps: remove sass-embedded as it comes with @rsbuild/plugin-sass
  package.json
Labels: release: patch, dependencies
